USE [master]
GO

CREATE DATABASE [Electronics]

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Electronics].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Electronics] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Electronics] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Electronics] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Electronics] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Electronics] SET ARITHABORT OFF 
GO

ALTER DATABASE [Electronics] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Electronics] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Electronics] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Electronics] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Electronics] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Electronics] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Electronics] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Electronics] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Electronics] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Electronics] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Electronics] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Electronics] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Electronics] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Electronics] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Electronics] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Electronics] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Electronics] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Electronics] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Electronics] SET  MULTI_USER 
GO

ALTER DATABASE [Electronics] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Electronics] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Electronics] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Electronics] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Electronics] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Electronics] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Electronics] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Electronics] SET  READ_WRITE 
GO

